### PR TITLE
fix: alignment of save as new button

### PR DESCRIPTION
**Pull request by vinayinvicible**
current alignment
Screenshot from 2024-05-19 00-27-31

new alignment
Screenshot from 2024-05-19 00-27-47

### CODE REVIEW

**Comment by vinayinvicible** [comment]
@lukasvinclav can you please check this?

**Comment by lukasvinclav** [comment]
How exactly I can reproduce the issue? I was not able to replicate the issue in current demo.

**Comment by vinayinvicible** [comment]
@lukasvinclav Sorry that I missed your comment.

You can check this by setting [save_as](https://docs.djangoproject.com/en/5.0/ref/contrib/admin/#django.contrib.admin.ModelAdmin.save_as) to `True` on any of the the `ModelAdmin`.

**Comment by vinayinvicible** [comment]
@lukasvinclav Can you please have another look at this.

**Pull request closed without merging**
