### PR TITLE
feat(tabs): custom lambda on link

### PR DESCRIPTION
**Pull request by Mte90**
image

Like in the screenshot but the link for bot the tabs is autogenerated by the object_id so like a page `http://127.0.0.1:8000/admin/portal/user/1/change/` will generate this link for the second tab `http://127.0.0.1:8000/admin/portal/userratings/1/change/`

Ref: #187

### CODE REVIEW

**Comment by Mte90** [comment]
Why is a wontfix?
There is something wrong with my code or the feature itself?

**Comment by Mte90** [comment]
@lukasvinclav can I have some hints why it was rejected?

**Comment by Mte90** [comment]
@lukasvinclav can I have some hints why it was rejected?

**Comment by dacodekid** [comment]
I hope this'll be merged.  Instead of Inline models, we could just link related models.

**Comment by Mte90** [comment]
Me too @dacodekid but I am not getting any reason why the PR was closed...

**Pull request closed without merging**
