### PR TITLE
Fix/add language dropdown

### PR DESCRIPTION
**Pull request by elias-ebrahimpour**
updated files:

- src/unfold/settings.py
- src/unfold/sites.py
- src/unfold/templates/unfold/helpers/language_switch.html
- src/unfold/templates/unfold/helpers/userlinks.html
- README.md

Description of changes:
I've added a new option for this theme. I added a dropdown, next to the User icon, for changing languages. It'll help Django developers to implement multilanguage much more easily and visually.

They have to know about [How Django discovers language preference](https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#how-django-discovers-language-preference).

Images:
Screenshot 1403-03-27 at 20 27 33
Screenshot 1403-03-27 at 20 27 46

### CODE REVIEW

**Review by omargawdat — APPROVED** [review]

**Comment by elias-ebrahimpour** [comment]
Hello again,

Would you please mention my account in the contributers section?

It can be useful for my resume.
Thank you.

**Comment by lukasvinclav** [comment]
Your contribution was not accepted as this feature is not planned.

**Comment by MaoMaoCake** [comment]
Is there a reason why this feature was not accepted? It doesn't have any changes that break existing code and is disabled by default.

**Comment by lukasvinclav** [comment]
@elias-ebrahimpour implemented in #854

**Comment by elias-ebrahimpour** [comment]
Thanks for making me aware.
It is my pleasure to be a contributor to this project. :)

**Pull request closed without merging**
